[tool.poetry]
name = "oreilly"
version = "0.1.0"
description = ""
authors = ["kzyoshida <kazunari.yoshida.ks@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^1.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
